apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak-customer-realm-openuinson
spec:
  approvePlan: "auto"
  interval: 1m
  path: ./terraform/keycloak/customer-realm
  sourceRef:
    kind: GitRepository
    name: k8s-test-cluster
    namespace: flux-system
  vars:
  - name: customer_realm_id
    value: customer-openuinson
  - name: customer_realm_name
    value: "Customer openuinson"
  - name: customer_realm_client_root_url
    value: "http://k8sou.127-0-0-1.nip.io"
  varsFrom:
  - kind: Secret
    name: keycloak-terraform-admin-client
    varsKeys:
    - clientId:terraform_client_id
    - clientSecret:terraform_client_secret
  - kind: Secret
    name: backend-client-secret-openuinson
    varsKeys:
    - clientId:customer_realm_backend_client_id
    - clientSecret:customer_realm_backend_client_secret