version: "3"
vars:
  CLUSTER_NAME: k8s-test-cluster
  K8S_VERSION: "v1.32.3"
  # TEST passwords only in clear
  POSTGRES_PASSWORD: postGresPassword123
  # TEST password only in clear
  KEYCLOAK_PASSWORD: keycloakPassword123
tasks:
  setup-k8s-context:
    internal: true
    cmds:
      - kubectl config use-context kind-{{.CLUSTER_NAME}}
  setup-cluster:
    desc: Create kind cluster if missing
    cmds:
      - |
        if kind get clusters | grep {{.CLUSTER_NAME}} &> /dev/null; then
          echo "cluster already present";
        else
          kind create cluster --name "{{.CLUSTER_NAME}}" --image "kindest/node:{{.K8S_VERSION}}" --wait 180s
        fi
  setup-flux-operator:
    desc:  Install flux operator with helm
    cmds:
      - task: setup-k8s-context
      - helm upgrade flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator --namespace flux-system --create-namespace --install
  install-flux-components:
    desc:  Apply the FluxInstance with kubectl to cluster
    cmds:
      - task: setup-k8s-context
      - kubectl apply -f cluster/flux-system/flux-instance.yaml
  create-secrets:
    desc: Create existing secrets needed
    cmds:
      - task: setup-k8s-context
      - kubectl -n keycloak create secret generic keycloak-admin-password --from-literal=postgresPassword={{.POSTGRES_PASSWORD}} --from-literal=adminPassword={{.KEYCLOAK_PASSWORD}}