version: "3"
vars:
  CLUSTER_NAME: k8s-test-cluster
  K8S_VERSION: "v1.32.3"
  # TEST passwords only in clear
  POSTGRES_PASSWORD: postGresPassword123
  # TEST password only in clear
  KEYCLOAK_PASSWORD: keycloakPassword123
  GIT_REPO_SSH: "ssh://git@github.com/umarhussain15/k8s-test-cluster.git"
  KEYCLOAK_TERRAFORM_CLIENT_ID: terraform-client
  KEYCLOAK_TERRAFORM_CLIENT_SECRET: some-very-strong-secret-id-here
env:
  SSH_PRIVATE_KEY_PATH: $HOME/.ssh/github_ed25519_ssh
tasks:
  setup-k8s-context:
    internal: true
    cmds:
      - kubectl config use-context kind-{{.CLUSTER_NAME}}
  delete-cluster:
    desc:  deletes the kind cluster
    cmds:
      - |
        if kind get clusters | grep {{.CLUSTER_NAME}} &> /dev/null; then
          kind delete cluster -n {{.CLUSTER_NAME}}
        else
          echo "{{.CLUSTER_NAME}} is not present"
        fi 
  setup-cluster:
    desc: Create kind cluster if missing
    cmds:
      - |
        if kind get clusters | grep {{.CLUSTER_NAME}} &> /dev/null; then
          echo "cluster already present";
        else
          kind create cluster --name "{{.CLUSTER_NAME}}" --image "kindest/node:{{.K8S_VERSION}}" --wait 180s
        fi
      - task: setup-k8s-context
      - kubectl create namespace flux-system -o yaml --dry-run=client | kubectl apply -f -
      - kubectl create namespace keycloak -o yaml --dry-run=client | kubectl apply -f -

  setup-flux-operator:
    desc:  Install flux operator with helm
    cmds:
      - task: setup-k8s-context
      - helm upgrade flux-operator oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator --namespace flux-system --create-namespace --install
  add-flux-ssh-secret:
    desc: create a k8s secret with ssh key from your host
    interactive: true
    cmds:
      - task: setup-k8s-context
      - |
          read -rsp "SSH key password: " ssh_password
          flux create secret git flux-system -n flux-system --url={{.GIT_REPO_SSH}} --private-key-file={{.SSH_PRIVATE_KEY_PATH}} --password=$ssh_password

  install-flux-components:
    desc:  Apply the FluxInstance with kubectl to cluster
    cmds:
      - task: setup-k8s-context
      - task: add-flux-ssh-secret
      - kubectl -n flux-system apply -f cluster/flux-system/flux-instance.yaml
      - |
          until kubectl get crd helmrepositories.source.toolkit.fluxcd.io >/dev/null 2>&1; do
            echo "Waiting for flux CRDs to be available..."
            sleep 5
          done
      - kubectl -n flux-system apply -f cluster/flux-system/helm-repos.yaml
      - kubectl -n flux-system apply -f cluster/flux-system/tofu-controller.yaml
  create-secrets:
    desc: Create existing secrets needed
    deps:
      - task: setup-cluster
    cmds:
      - task: setup-k8s-context
      - kubectl -n keycloak create secret generic keycloak-admin-password --from-literal=postgresPassword={{.POSTGRES_PASSWORD}} --from-literal=adminPassword={{.KEYCLOAK_PASSWORD}} -o yaml --dry-run=client | kubectl apply -f -
      - kubectl -n keycloak create secret generic keycloak-terraform-admin-client --from-literal=clientId={{.KEYCLOAK_TERRAFORM_CLIENT_ID}} --from-literal=clientSecret={{.KEYCLOAK_TERRAFORM_CLIENT_SECRET}} -o yaml --dry-run=client | kubectl apply -f -
      - kubectl -n flux-system create secret generic keycloak-terraform-admin-client --from-literal=clientId={{.KEYCLOAK_TERRAFORM_CLIENT_ID}} --from-literal=clientSecret={{.KEYCLOAK_TERRAFORM_CLIENT_SECRET}} -o yaml --dry-run=client | kubectl apply -f -