apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fluent-bit
spec:
  chart:
    spec:
      chart: fluent-bit
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      version: '*'
  install:
    crds: CreateReplace
  interval: 10m0s
  upgrade:
    crds: CreateReplace
  values:
    # config:
    #   outputs: |
    #     [OUTPUT]
    #         Name                 opentelemetry
    #         Match                *
    #         Host                 signoz-otel-collector
    #         Port                 4318
    #         grpc                 off
    #         Metrics_uri          /v1/metrics
    #         Logs_uri             /v1/logs
    #         Traces_uri           /v1/traces
    #         Tls                  Off
    #         Tls.verify           Off
    #         Log_response_payload True
    #         logs_span_id_message_key span_id
    #         logs_trace_id_message_key trace_id
    #         logs_severity_text_message_key loglevel
    #         logs_severity_number_message_key lognum
    #         # add user-defined labels
    #         add_label            app fluent-bit
    dashboards:
      enabled: true
    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 100Mi