apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  interval: 5m
  chart:
    spec:
      chart: keycloak
      version: "24.x.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    global:
      security:
        allowInsecureImages: true
    auth:
      adminUser: keycloak-admin
      existingSecret: keycloak-admin-password
      passwordSecretKey: adminPassword
    proxy: edge
    production: true
    replicaCount: 1
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 0.5
        memory: 500Mi
    ingress:
      enabled: false
    adminIngress:
      enabled: false
    metrics:
      enabled: false
      serviceMonitor:
        enabled: true
    postgresql:
      image:
        tag: 16.4.0-debian-12-r14 # pin postgres version to 16 as keycloak only supports this in v26
      # architecture: replication
      auth:
        username: bn_keycloak
        existingSecret: keycloak-admin-password
        secretKeys:
          userPasswordKey: postgresPassword
          adminPasswordKey: postgresPassword
    keycloakConfigCli:
      enabled: true
      extraEnvVars:
      - name: IMPORT_VARSUBSTITUTION_ENABLED
        value: "true"
      - name: TERRAFORM_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: keycloak-terraform-admin-client
            key: clientId
      - name: TERRAFORM_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: keycloak-terraform-admin-client
            key: clientSecret
      configuration:
        master.json: |
          {
            "realm": "master",
            "clients": [
              {
                "clientId": "$(env:TERRAFORM_CLIENT_ID)",
                "name": "terraform-client",
                "clientAuthenticatorType": "client-secret",
                "secret": "$(env:TERRAFORM_CLIENT_SECRET)",
                "description": "client for terraform to manage the realms",
                "rootUrl": "",
                "adminUrl": "",
                "baseUrl": "",
                "enabled": true,
                "alwaysDisplayInConsole": false,
                "redirectUris": [
                  "/*"
                ],
                "webOrigins": [
                  "/*"
                ],
                "notBefore": 0,
                "bearerOnly": false,
                "consentRequired": false,
                "standardFlowEnabled": false,
                "implicitFlowEnabled": false,
                "directAccessGrantsEnabled": false,
                "serviceAccountsEnabled": true,
                "publicClient": false,
                "frontchannelLogout": true,
                "protocol": "openid-connect",
                "fullScopeAllowed": true,
                "defaultClientScopes": [
                  "web-origins",
                  "service_account",
                  "acr",
                  "roles",
                  "profile",
                  "basic",
                  "email"
                ],
                "optionalClientScopes": [
                  "address",
                  "phone",
                  "organization",
                  "offline_access",
                  "microprofile-jwt"
                ]
              }
            ]
          }