apiVersion: v1
type: Opaque
metadata:
  name: orchestra-secrets-source
stringData:
  K8S_DB_SECRET: some-strong-secret-here
  unisonKeystorePassword: some-very-strong-secret-here
  OIDC_CLIENT_SECRET:  customer-openuinson-secret
kind: Secret