apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
spec:
  chart:
    spec:
      chart: signoz
      version: 0.79.x
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  interval: 10m0s
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    otelCollector:
      ports:
            fluentforward:
              enabled: true
              containerPort: 24224
              servicePort: 24224
              nodePort: ""
              protocol: TCP
      config:
        receivers:
          fluentforward:
            endpoint: 0.0.0.0:24224
        service:
          pipelines:
            logs:
              receivers: [otlp, fluentforward, httplogreceiver/json]
              processors: [batch]
              exporters: [clickhouselogsexporter, metadataexporter]

