apiVersion: v1
kind: Secret
metadata:
  name: backend-client-secret-openuinson
  annotations:
    info: "Added here for testing, in prod it gets injected via a secret service e.g. external secrets"
type: Opaque
stringData:
  clientId: customer-backend
  clientSecret: customer-openuinson-secret
