apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: controlplaneio
spec:
  interval: 1m
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tofu-controller
spec:
  interval: 1m
  url: https://flux-iac.github.io/tofu-controller
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h0m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
spec:
  interval: 1h0m0s
  url:  https://fluent.github.io/helm-charts
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: signoz
spec:
  interval: 1h0m0s
  url:  https://charts.signoz.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-telemetry
spec:
  interval: 1h0m0s
  url:  https://open-telemetry.github.io/opentelemetry-helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
spec:
  interval: 1h0m0s
  url:  https://charts.jetstack.io

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
spec:
  interval: 1h0m0s
  url:  https://kyverno.github.io/kyverno/
