apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: controlplaneio
spec:
  interval: 1m
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/
  type: oci
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tofu-controller
spec:
  interval: 1m
  url: https://flux-iac.github.io/tofu-controller
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
spec:
  interval: 1h0m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts