apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: keycloak
spec:
  approvePlan: "" # or you can omit this field
  interval: 1m
  path: ./cluster/terraform/keycloak
  sourceRef:
    kind: GitRepository
    name: k8s-test-cluster
    namespace: flux-system
  varsFrom:
  - kind: Secret
    name: keycloak-terraform-admin-client
    varsKeys:
    - clientId:client_id
    - clientSecret:client_secret